export const TRAER_TODOS = 'publicaciones_traer_todos'
export const CARGANDO = 'publicaciones_cargando'
export const ERROR = 'publicaciones_error'
export const URL_API = 'https://jsonplaceholder.typicode.com/posts'
export const ACTUALIZAR = 'publicaciones_actualizar'
export const COM_CARGANDO = 'comunicacion_cargando'
export const COM_ERROR = 'comunicacion_error'
export const COM_ACTUALIZAR = 'comunicacion_atualizar'
