export const TRAER_TODAS = 'tareas_traer_todas'
export const CARGANDO = 'tareas_cargando'
export const ERROR = 'tareas_error'
export const CAMB_USUARIO_ID = 'tareas_cambio_usuario_id'
export const CAMB_TITULO = 'tareas_cambio_titulo'
export const GUARDAR = 'tareas_guardar'
export const ACTUALIZAR = 'tareas_actualizadas'
export const LIMPIAR = 'tareas_limpiar'
